# Build both 64 bit and 32 bit versions of this driver.

env = Environment(
       tools = ['winddk'],
       DDK_VERSION='7600.16385.1',
       TARGET_OS='wnet',
       TARGET_ARCH='x64',
       BUILD_TYPE = 'chk')

files = env.DDKBuild()

env = Environment(
       tools = ['winddk'],
       DDK_VERSION='7600.16385.1',
       TARGET_OS='wnet',
       TARGET_ARCH='x86',
       BUILD_TYPE = 'chk')

files = env.DDKBuild()

